import {
  Bar,
  BarChart,
  ResponsiveContainer,
  Tooltip,
  XAxis,
  YAxis,
} from "recharts";
import type { Fuel, GenerationSource } from "../types/generationMix";

type props = {
  sources: GenerationSource[];
};

const FUEL_COLORS: Record<Fuel, string> = {
  wind: "#60a5fa",
  solar: "#fbbf24",
  hydro: "#22d3ee",
  nuclear: "#a78bfa",
  biomass: "#84cc16",
  gas: "#f97316",
  coal: "#52525b",
  imports: "#94a3b8",
  other: "#71717a",
};

const FUEL_LABELS: Record<Fuel, string> = {
  wind: "Wind",
  solar: "Solar",
  hydro: "Hydro",
  nuclear: "Nuclear",
  biomass: "Biomass",
  gas: "Gas",
  coal: "Coal",
  imports: "Imports",
  other: "Other",
};

export function GenerationMixChart({ sources }: props) {
  function CustomBarShape(props: any) {
    const { x, y, width, height, payload } = props;
    return (
      <rect
        x={x}
        y={y}
        width={width}
        height={height}
        rx={4}
        ry={4}
        fill={payload?.color ?? "#64748b"}
      />
    );
  }
  const data: GenerationSource[] = [...sources]
    .sort((a, b) => b.perc - a.perc)
    .map((source) => ({
      fuel: source.fuel,
      label: FUEL_LABELS[source.fuel],
      perc: source.perc,
      color: FUEL_COLORS[source.fuel],
    }));
  return (
    <div className="bg-zinc-800/50 border border-zinc-800 rounded-2xl p-6 sm:p-8">
      <p className="text-zinc-400 text-sm uppercase tracking-wide">
        Generation mix
      </p>
      <p className="text-zinc-300 text-sm mt-1 mb-6">
        Share of UK electricity generated by fuel type, right now
      </p>

      <ResponsiveContainer width="100%" height={320}>
        <BarChart
          data={data}
          layout={"vertical"}
          margin={{ top: 0, right: 0, left: 0, bottom: 0 }}
        >
          <XAxis
            type="number"
            domain={[0, 100]}
            tickFormatter={(v) => `${v}%`}
            stroke="#71717a"
            tick={{ fill: "#e4e4e7", fontSize: 12 }}
          />
          <YAxis
            type="category"
            dataKey="label"
            stroke="#71717a"
            tick={{ fill: "#e4e4e7", fontSize: 13 }}
            width={80}
          />
          <Tooltip
            cursor={{ fill: "rgba(255,255,255,0.04)" }}
            contentStyle={{
              background: "#18181b",
              border: "1px solid #27272a",
              borderRadius: 8,
              color: "#e4e4e7",
            }}
            formatter={(value) => [
              `${Number(value ?? 0).toFixed(1)}%`,
              "Share",
            ]}
          />
          <Bar
            dataKey="perc"
            radius={[0, 4, 4, 0]}
            shape={(props) => <CustomBarShape {...props} />}
          />
        </BarChart>
      </ResponsiveContainer>
    </div>
  );
}
